services:
  - type: web
    name: mentBlog
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mentBlog.wsgi"
    deployCommand: "python manage.py migrate"
